name: Java CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.5
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.5'
    - name: Build with Maven
      run: mvn -B package --file pom.xml clean verify -Dmockserver.initializationJsonPath=src/test/resources/REST/mockserver/initialize.json
